name: Reusable build

on:
  workflow_call:
    inputs:
      caller_sha:
        required: true
        type: string
      repo:
        required: true
        type: string
      actor:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ runner.os }}-buildx-${{ inputs.caller_sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./${{ inputs.dockerfile }}
          push: false
          tags: 'test_dev_build'
          labels: 'dependabot'
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache
          build-args:  |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
