name: Reusable build

on:
  workflow_call:
    inputs:
      tags:
        required: false
        type: string
        default: test_dev_build
      labels:
        required: false
        type: string
        default: dependabot
      dockerfile:
        required: false
        type: string
        default: Dockerfile
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./${{ inputs.dockerfile }}
          push: false
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          build-args:  |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
