name: Reusable coverage for Node

on:
  workflow_call:
    inputs:
      coverage_file_path:
        required: true
        type: string
      node_version:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  coverage:
    name: Run tests and upload coverage report to codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ inputs.node_version }}

      - name: npm install, lint, and test
        run: |
          npm ci
          npm run lint:project
          npm test
        env:
          CI: true

      - name: Report coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: ${{ inputs.coverage_file_path }}
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
