name: Reusable coverage for Node

on:
  workflow_call:
    inputs:
      coverage_file_path:
        required: true
        type: string
      node_version:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  coverage:
    name: Run tests and upload coverage report to codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: npm install, lint, and test
        run: |
          npm ci
          npm run lint:project
          npm test
        env:
          CI: true

      - name: Report coverage
        uses: codecov/codecov-action@v5
        with:
          files: ${{ inputs.coverage_file_path }}
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
