name: Reusable coverage for Node

on:
  workflow_call:
    inputs:
      coverage_file_path:
        required: true
        type: string
      node_version:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  coverage:
    name: Run tests and upload coverage report to codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ inputs.node_version }}

      - name: npm install, lint, and test
        run: |
          npm ci
          npm run lint:project
          npm test
        env:
          CI: true

      - name: Report coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: ${{ inputs.coverage_file_path }}
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
