name: Reusable coverage for Go

on:
  workflow_call:
    inputs:
      coverage_file_path:
        required: true
        type: string
      go_version:
        required: true
        type: string
      test_path:
        required: false
        type: string
        default: ./
    secrets:
      GH_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  coverage:
    name: Run tests and upload coverage report to codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ inputs.go_version }}
          cache: true

      - name: Test
        run: go test -v -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ${{ inputs.test_path }}

      - name: Report coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: ${{ inputs.coverage_file_path }}
          token: ${{ secrets.CODECOV_TOKEN }}
