name: Reusable coverage for Go

on:
  workflow_call:
    inputs:
      coverage_file_path:
        required: true
        type: string
      go_version:
        required: true
        type: string
      test_path:
        required: false
        type: string
        default: ./
    secrets:
      GH_TOKEN:
        required: true

jobs:
  coverage:
    name: Run tests and upload coverage report to codecov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: ${{ inputs.go_version }}
          cache: true

      - name: Test
        run: go test -v -race -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ${{ inputs.test_path }}

      - name: Report coverage
        uses: codecov/codecov-action@v3
        with:
          files: ${{ inputs.coverage_file_path }}
