name: Reusable lint for NPM/Node projects

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      install_args:
        required: false
        type: string
      eslint_version:
        required: true
        type: string
      lint_args:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js ${{ inputs.node_version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci ${{ inputs.install_args }}
          npm install --no-save eslint@${{ inputs.eslint_version }}

      - name: Run linter
        run: |
          npx eslint ${{ inputs.lint_args }}
