name: Reusable workflow for pip audit
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      python_architecture:
        required: false
        type: string
        default: x64
      venv_name:
        required: false
        type: string
        default: ""
    secrets:
      GH_TOKEN:
        required: true
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ inputs.python_version }}
          architecture: ${{ inputs.python_architecture }}

      - name: Install dependencies
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install --constraint=.github/workflows/constraints.txt pipx
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry config virtualenvs.in-project true
          poetry install

      - name: Upgrade pip in virtual environment
        run: |
          if [ -n "${{ inputs.venv_name }}" ]; then
            .venv/${{ inputs.venv_name }}/bin/pip install --upgrade --constraint=.github/workflows/constraints.txt pip
          else
            .venv/bin/pip install --upgrade --constraint=.github/workflows/constraints.txt pip
          fi

      - name: Run audit
        uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 # v1.1.0
        with:
          virtual-environment: .venv/${{ inputs.venv_name }}
          summary: true
