name: Release Drafter
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
        with:
          token: ${{ secrets.GH_TOKEN }}
