name: Release
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      python_architecture:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      PYPI_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          architecture: x64

      - name: Install dependencies
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
          pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry

      - name: Publish
        run: |
          nox --python ${{ inputs.python_version }}
          poetry build
          poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
