name: Release Drafter
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@v5.19.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
