name: Upload files
on:
  workflow_call:
    inputs:
      destination_dir:
        required: false
        type: string
        default: ''
      program_html:
        required: false
        type: string
      program_epub:
        required: false
        type: string
      program_pdf:
        required: false
        type: string
      program:
        required: false
        type: string
      publish_branch:
        required: true
        type: string
      publish_dir:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build_adoc_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: asciidoctor build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build html
      id: adocbuild_html
      if: ${{ inputs.program_html != '' }}
      uses: tonynv/asciidoctor-action@v2
      with:
        program: ${{ inputs.program_html }}

    - name: Build epub
      id: adocbuild_epub
      if: ${{ inputs.program_epub != '' }}
      uses: tonynv/asciidoctor-action@v2
      with:
        program: ${{ inputs.program_epub }}

    - name: Build pdf
      id: adocbuild_pdf
      if: ${{ inputs.program_pdf != '' }}
      uses: tonynv/asciidoctor-action@v2
      with:
        program: ${{ inputs.program_pdf }}

    - name: Build generic
      id: adocbuild_pdf
      if: ${{ inputs.program != '' }}
      uses: tonynv/asciidoctor-action@v2
      with:
        program: ${{ inputs.program }}

    - name: Deploy w/destination
      if: ${{ inputs.destination_dir != '' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_branch: ${{ inputs.publish_branch }}
        publish_dir: ${{ inputs.publish_dir }}
        destination_dir: ${{ inputs.destination_dir }}

    - name: Deploy w/o destination
      if: ${{ inputs.destination_dir == '' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_branch: ${{ inputs.publish_branch }}
        publish_dir: ${{ inputs.publish_dir }}
