name: Build adocs and deploy specification to Github Pages
on:
  workflow_call:
    inputs:
      files:
        required: true
        type: string
      host:
        required: true
        type: string
      ontology:
        required: true
        type: string
      ontology-type:
        required: true
        type: string
      program_html:
        required: false
        type: string
      program_epub:
        required: false
        type: string
      program_pdf:
        required: false
        type: string
      ref:
        required: false
        type: string
        default: ${{ github.ref }}
    secrets:
      GH_TOKEN:
        required: true
      STATIC_RDF_SERVER_API_KEY:
        required: true

jobs:
  upload_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Build html
        id: adocbuild_html
        uses: tonynv/asciidoctor-action@v2
        with:
          program: ${{ inputs.program_html }}

      - name: Build epub
        id: adocbuild_epub
        uses: tonynv/asciidoctor-action@v2
        with:
          program: ${{ inputs.program_epub }}

      - name: Build pdf
        id: adocbuild_pdf
        uses: tonynv/asciidoctor-action@v2
        with:
          program: ${{ inputs.program_pdf }}

      - name: Upload files to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-files
        with:
          ontology-type: ${{ inputs.ontology-type }}
          ontology: ${{ inputs.ontology }}
          host: ${{ inputs.host }}
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            ${{ inputs.files }}
