name: Run nox tests
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      python_architecture:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          architecture: ${{ inputs.python_architecture}}

      - name: Install dependencies
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip install --constraint=.github/workflows/constraints.txt pipx
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry

      - name: Run tests
        run: nox --python ${{ inputs.python_version }}
