# .github/workflows/test-pypi.yml
name: TestPyPI
on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      python_architecture:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      TEST_PYPI_TOKEN:
        required: true

jobs:
  test_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
          architecture: ${{ inputs.python_architecture}}

      - name: Install poetry
        run: pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry

      - name: Set TestPyPi version
        run: >-
          poetry version patch &&
          version=$(poetry version | awk '{print $2}') &&
          poetry version $version.dev.$(date +%s)

      - name: Build
        run: poetry build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.0
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
